/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ra47_2014_jnivezba_FibonacciNative */

#ifndef _Included_com_example_ra47_2014_jnivezba_FibonacciNative
#define _Included_com_example_ra47_2014_jnivezba_FibonacciNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ra47_2014_jnivezba_FibonacciNative
 * Method:    get
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ra47_12014_jnivezba_FibonacciNative_get
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
