/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ra47_2014_pnrs1_rtrk_taskmanager_CalculateStatistics */

#ifndef _Included_ra47_2014_pnrs1_rtrk_taskmanager_CalculateStatistics
#define _Included_ra47_2014_pnrs1_rtrk_taskmanager_CalculateStatistics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ra47_2014_pnrs1_rtrk_taskmanager_CalculateStatistics
 * Method:    calculate
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ra47_12014_pnrs1_rtrk_taskmanager_CalculateStatistics_calculate
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
